/*
 * The Cards Against Humanity Main Deck (v2.4): 100 black cards, 500 white.
 *
 * Transcribed from the print-and-play PDF the publisher gives away. The text in
 * that PDF is outlined vector paths — no fonts, no images — so this was read off
 * rendered pages rather than extracted, and deck.test.ts is what holds the
 * counts honest.
 *
 * Cards Against Humanity is free to use under Creative Commons BY-NC-SA 2.0.
 * See NOTICE.md in this directory. The code around it stays BSD-3-Clause; the
 * cards do not, which is why they live in one file that is easy to lift out.
 *
 * Typographic apostrophes and quotes are deliberate — they match the printed
 * cards, and they let every string sit in ordinary single quotes unescaped.
 */

import type { BlackCard } from './cards.ts';

export const BLACK: BlackCard[] = [
  { text: 'Hey Reddit! I’m ____. Ask me anything.', pick: 1 },
  { text: 'Introducing X-treme Baseball! It’s like baseball, but with ____!', pick: 1 },
  { text: 'What is Batman’s guilty pleasure?', pick: 1 },
  { text: 'TSA guidelines now prohibit ____ on airplanes.', pick: 1 },
  { text: 'Next from J.K. Rowling: Harry Potter and the Chamber of ____.', pick: 1 },
  { text: 'That’s right, I killed ____. How, you ask? ____.', pick: 2 },
  { text: 'I’m sorry, Professor, but I couldn’t complete my homework because of ____.', pick: 1 },
  { text: 'And the Academy Award for ____ goes to ____.', pick: 2 },
  { text: 'Dude, do not go in that bathroom. There’s ____ in there.', pick: 1 },
  { text: 'How did I lose my virginity?', pick: 1 },
  { text: 'It’s a pity that kids these days are all getting involved with ____.', pick: 1 },
  { text: 'Step 1: ____. Step 2: ____. Step 3: Profit.', pick: 2 },
  { text: '____. Betcha can’t have just one!', pick: 1 },
  { text: 'Kids, I don’t need drugs to get high. I’m high on ____.', pick: 1 },
  { text: 'For my next trick, I will pull ____ out of ____.', pick: 2 },
  { text: 'Mitch McConnell can’t cum without ____.', pick: 1 },
  {
    text: 'In the new Disney Channel Original Movie, Hannah Montana struggles with ____ for the first time.',
    pick: 1,
  },
  { text: 'What’s my secret power?', pick: 1 },
  { text: 'I’m going on a cleanse this week. Nothing but kale juice and ____.', pick: 1 },
  { text: '____ + ____ = ____.', pick: 3 },
  { text: 'When Pharaoh remained unmoved, Moses called down a Plague of ____.', pick: 1 },
  { text: 'Just once, I’d like to hear you say “Thanks, Mom. Thanks for ____.”', pick: 1 },
  { text: 'Daddy, why is mommy crying?', pick: 1 },
  { text: 'When I was tripping on acid, ____ turned into ____.', pick: 2 },
  { text: '50% of all marriages end in ____.', pick: 1 },
  { text: 'My fellow Americans: Before this decade is out, we will have ____ on the moon!', pick: 1 },
  {
    text: 'This season at Steppenwolf, Samuel Beckett’s classic existential play: Waiting for ____.',
    pick: 1,
  },
  { text: 'Instead of coal, Santa now gives the bad children ____.', pick: 1 },
  {
    text: 'Life for American Indians was forever changed when the White Man introduced them to ____.',
    pick: 1,
  },
  { text: 'What’s Teach For America using to inspire inner city students to succeed?', pick: 1 },
  { text: 'Maybe she’s born with it. Maybe it’s ____.', pick: 1 },
  {
    text: 'My name is Peter Parker. I was bitten by a radioactive spider, and now I’m ____.',
    pick: 1,
  },
  { text: 'White people like ____.', pick: 1 },
  { text: '____ is a slippery slope that leads to ____.', pick: 2 },
  { text: 'Why do I hurt all over?', pick: 1 },
  { text: 'A romantic, candlelit dinner would be incomplete without ____.', pick: 1 },
  { text: 'Just saw this upsetting video! Please retweet!! #stop____', pick: 1 },
  {
    text: 'Fun tip! When your man asks you to go down on him, try surprising him with ____ instead.',
    pick: 1,
  },
  { text: 'The class field trip was completely ruined by ____.', pick: 1 },
  { text: 'What’s a girl’s best friend?', pick: 1 },
  { text: 'Dear Abby, I’m having some trouble with ____ and would like your advice.', pick: 1 },
  {
    text: 'In Jordan Peele’s new thriller, a young family discovers that ____ had really been ____ all along.',
    pick: 2,
  },
  { text: 'When I am President, I will create the Department of ____.', pick: 1 },
  { text: 'What are my parents hiding from me?', pick: 1 },
  { text: 'What never fails to liven up the party?', pick: 1 },
  { text: 'IF you like ____, YOU MIGHT BE A REDNECK.', pick: 1 },
  { text: 'Make a haiku.', pick: 1 },
  { text: 'What made my first kiss so awkward?', pick: 1 },
  {
    text: 'Hey guys, welcome to Chili’s! Would you like to start the night off right with ____?',
    pick: 1,
  },
  { text: 'I got 99 problems but ____ ain’t one.', pick: 1 },
  { text: '____. It’s a trap!', pick: 1 },
  { text: 'Hulu’s new reality show features twelve hot singles living with ____.', pick: 1 },
  { text: 'What would grandma find disturbing, yet oddly charming?', pick: 1 },
  { text: '____. That was so metal.', pick: 1 },
  { text: 'I never truly understood ____ until I encountered ____.', pick: 2 },
  { text: 'During sex, I like to think about ____.', pick: 1 },
  { text: 'What ended my last relationship?', pick: 1 },
  { text: 'What’s that sound?', pick: 1 },
  { text: 'Uh, hey guys, I know this was my idea, but I’m having serious doubts about ____.', pick: 1 },
  { text: 'Why am I sticky?', pick: 1 },
  { text: 'I’m no doctor, but I’m pretty sure what you’re suffering from is called “____.”', pick: 1 },
  { text: 'What’s there a ton of in heaven?', pick: 1 },
  {
    text: 'After four platinum albums and three Grammys, it’s time to get back to my roots, to what inspired me to make music in the first place: ____.',
    pick: 1,
  },
  { text: 'What will always get you laid?', pick: 1 },
  {
    text: 'They said we were crazy. They said we couldn’t put ____ inside of ____. They were wrong.',
    pick: 2,
  },
  { text: 'Lifetime® presents “____: the Story of ____.”', pick: 2 },
  { text: '____: kid-tested, mother-approved.', pick: 1 },
  { text: 'Why can’t I sleep at night?', pick: 1 },
  { text: 'What’s that smell?', pick: 1 },
  { text: 'Why is Brett so sweaty?', pick: 1 },
  {
    text: 'This is the way the world ends\nThis is the way the world ends\nNot with a bang but with ____.',
    pick: 1,
  },
  { text: 'Coming to Broadway this season, ____: The Musical.', pick: 1 },
  {
    text: 'Here is the church\nHere is the steeple\nOpen the doors\nAnd there is ____.',
    pick: 1,
  },
  { text: 'But before I kill you, Mr. Bond, I must show you ____.', pick: 1 },
  {
    text: 'A recent laboratory study shows that undergraduates have 50% less sex after being exposed to ____.',
    pick: 1,
  },
  { text: 'Introducing the amazing superhero/sidekick duo! It’s ____ and ____!', pick: 2 },
  { text: 'Next on ESPN2: The World Series of ____.', pick: 1 },
  { text: 'When I am a billionaire, I shall erect a 50-foot statue to commemorate ____.', pick: 1 },
  {
    text: 'Military historians remember Alexander the Great for his brilliant use of ____ against the Persians.',
    pick: 1,
  },
  { text: 'War! What is it good for?', pick: 1 },
  { text: 'What gives me uncontrollable gas?', pick: 1 },
  {
    text: 'The new Chevy Tahoe. With the power and space to take ____ everywhere you go.',
    pick: 1,
  },
  { text: 'Well if you’ll excuse me, gentlemen, I have a date with ____.', pick: 1 },
  { text: 'Alternative medicine is now embracing the curative powers of ____.', pick: 1 },
  { text: 'As the mom of five rambunctious boys, I’m no stranger to ____.', pick: 1 },
  { text: '____. High five, bro.', pick: 1 },
  { text: 'Today on Maury: “Help! My son is ____!”', pick: 1 },
  { text: 'I get by with a little help from ____.', pick: 1 },
  { text: '★☆☆☆☆ Do NOT go here! Found ____ in my fettuccine alfredo!', pick: 1 },
  { text: 'I drink to forget ____.', pick: 1 },
  { text: 'I’m LeBron James, and when I’m not slamming dunks, I love ____.', pick: 1 },
  { text: 'What makes life worth living?', pick: 1 },
  { text: 'Arby’s: We Have ____.', pick: 1 },
  {
    text: 'Mr. and Mrs. Diaz, we called you in because we’re concerned about Cynthia. Are you aware that your daughter is ____?',
    pick: 1,
  },
  { text: 'If you can’t be with the one you love, love ____.', pick: 1 },
  { text: 'Brought to you by Bud Light®, the Official Beer of ____.', pick: 1 },
  { text: 'Click Here for ____!!!', pick: 1 },
  { text: 'Check me out, yo! I call this dance move “____.”', pick: 1 },
  { text: 'Old MacDonald had ____. E-I-E-I-O.', pick: 1 },
  { text: 'Men’s Wearhouse: You’re gonna like ____. I guarantee it.', pick: 1 },
];

export const WHITE: string[] = [
  'Silence.',
  'The illusion of choice in a late-stage capitalist society.',
  'Many bats.',
  'Hot Asian men.',
  'Shame.',
  'Website.',
  'Assaulting a police officer.',
  'Magnets.',
  'A sorry excuse for a father.',
  'Seeing what happens when you lock people in a room with hungry seagulls.',
  'A crucifixion.',
  'A narc.',
  'Boneless buffalo wings.',
  'A live studio audience.',
  'Complaining.',
  'Authentic Mexican cuisine.',
  'Doing crimes.',
  'COVID-19.',
  'Crippling debt.',
  'Daddy issues.',
  'Working in an Amazon warehouse.',
  'A fart so powerful that it wakes the giants from their thousand-year slumber.',
  'Former President George W. Bush.',
  'Full frontal nudity.',
  'Covering myself with Parmesan cheese and chili flakes because I am pizza.',
  'Laying an egg.',
  'Getting naked and watching Nickelodeon.',
  'Pretending to care.',
  'Having big dreams but no realistic way to achieve them.',
  'Seeing Grandma naked.',
  'Boogers.',
  'The Confederate flag.',
  'The miracle of childbirth.',
  'A positive attitude!',
  'Having a stroke.',
  'White privilege.',
  'Emerging from the sea and rampaging through Tokyo.',
  'The Hamburglar.',
  'The tampon from my vagina.',
  'The Blood of Christ.',
  'Soft, kissy missionary sex.',
  'BATMAN!',
  'Agriculture.',
  'Barely making $25,000 a year.',
  'Natural selection.',
  'Boomers.',
  'Dropping a hot doodie out of my turd hole.',
  'My abusive boyfriend who really isn’t so bad once you get to know him.',
  'Prescription pain killers.',
  'Swooping.',
  'Mansplaining.',
  'A homoerotic volleyball montage.',
  'Alexandria Ocasio-Cortez.',
  'Putting things where they go.',
  'Holding a pepper grinder for some reason.',
  'Giving birth in prison.',
  'An old guy who’s almost dead.',
  'Kanye West.',
  'Hot cheese.',
  'Getting serial killed.',
  'Seven dead and three in critical condition.',
  'Smegma.',
  'Alcoholism.',
  'A middle-aged man on roller skates.',
  'Nobody giving a shit about anything anymore.',
  'Grabbing my man by his love handles and fucking his big ass.',
  'Stuffing my peehole with Tic Tacs.',
  'Self-loathing.',
  'Sitting on my face and telling me I’m garbage.',
  'Half-assed foreplay.',
  'The Holy Bible.',
  'German dungeon porn.',
  'Being on fire.',
  'Using comedy as a coping mechanism.',
  'Gandhi.',
  'Your weird brother.',
  'Birth control.',
  'Nasty shit, like real sick stuff.',
  'An erection that lasts longer than four hours.',
  'A three-way with my wife and Shaquille O’Neal.',
  'The past.',
  'My genitals.',
  'An endless stream of diarrhea.',
  'Science.',
  'Not reciprocating oral sex.',
  'Flightless birds.',
  'A good sniff.',
  '50,000 volts straight to the nipples.',
  'Da clurb.',
  'Dead birds everywhere.',
  'The arrival of the pizza.',
  'Permanent Orgasm-Face Disorder.',
  'The cool, refreshing taste of Pepsi.®',
  'Irritable bowel syndrome.',
  'Oprah.',
  'Wondering if it’s possible to get some of that salsa to go.',
  'Bananas.',
  'Cringe.',
  'Me jubbly bubblies.',
  'Switching to Geico.®',
  'Peeing a little bit.',
  'Wet dreams.',
  'The Jews.',
  'My cheating son-of-a-bitch husband.',
  'Powerful thighs.',
  'These hoes.',
  'The only gay person in a hundred miles.',
  'Having sex for the first time.',
  'Donald J. Trump.',
  'Kissing grandma on the forehead and turning off her life support.',
  'A certain je ne sais quoi.',
  'An AR-15 assault rifle.',
  'My good bra.',
  'Punching a congressman in the face.',
  'Saying everything is okay when everything is clearly not okay.',
  'Being rich.',
  'Floating down the Hudson River with the other garbage.',
  'Republicans.',
  'Sniffing and kissing my feet.',
  'A much younger woman.',
  'Poverty.',
  'Kamala Harris.',
  'Committing suicide.',
  'A loser like you.',
  'A mistake.',
  'Squirting.',
  'Wizard music.',
  'The Kool-Aid Man.',
  'Explaining the difference between sex and gender.',
  'Free samples.',
  'Hurting those closest to me.',
  'Feeding strawberries to my manslut.',
  'The Three-Fifths Compromise.',
  'Lactation.',
  'Laughing over champagne flutes while the poor freeze to death outside.',
  'Shutting up so I can watch the game.',
  'Eating a hard boiled egg out of my husband’s asshole.',
  'Doing white people shit with a bunch of white people.',
  'One titty hanging out.',
  'Fucking all my dad’s friends.',
  'Drinking gasoline to see what it tastes like.',
  'Inappropriate yodeling.',
  'Puberty.',
  'Ghosts.',
  '50 mg of Zoloft daily.',
  'Fucking my sister.',
  'Braiding three penises into a Twizzler.',
  'Vigorous jazz hands.',
  'Getting fingered.',
  'My Uber driver, Pavel.',
  'GoGurt.®',
  'Police brutality.',
  'An abortion.',
  'Preteens.',
  'My fat daughter.',
  'Clean drinking water.',
  'Fading away into nothingness.',
  'Darth Vader.',
  'A sad handjob.',
  'Exactly what you’d expect.',
  'Critical race theory.',
  'Adderall.®',
  'Your mom.',
  'Sideboob.',
  'An octopus giving seven handjobs and smoking a cigarette.',
  'My neck, my back, my pussy, and my crack.',
  'J.D. Power and his associates.',
  'Mouth herpes.',
  'Sperm whales.',
  'Women of color.',
  'Men discussing their feelings in an emotionally healthy way.',
  'Incest.',
  'Pac-Man uncontrollably guzzling cum.',
  'Casually suggesting a threesome.',
  'Running out of semen.',
  'God.',
  'Backing over a kid with the Buick.',
  'Pissing in my thirsty mouth.',
  'Emotions.',
  'Licking things to claim them as your own.',
  'Jobs.',
  'The placenta.',
  'Lips that could suck the chrome off a doorknob.',
  'The Bachelorette season finale.',
  'Throwing grapes at a man until he loses touch with reality.',
  'Establishing dominance.',
  'Finger painting.',
  'Old-people smell.',
  'Getting crushed by a vending machine.',
  'My inner demons.',
  'A Super Soaker™ full of cat pee.',
  'Aunt Jemima’s® racist pancake sauce.',
  'Cuddling.',
  'However much weed $20 can buy.',
  'Battlefield amputations.',
  'Spaghetti? Again?',
  'Ronald Reagan.',
  'A disappointing birthday party.',
  'Nachos for the table.',
  'Becoming a blueberry.',
  'A tiny horse.',
  'Crab.',
  'Selling crack to children.',
  'The Wendy’s Spicy Chicken Sandwich.',
  'Brown people.',
  'Sexually active band geeks.',
  'Pedophiles.',
  'Yeast.',
  'How bad my daughter fucked up her dance recital.',
  'Rectangles.',
  'Being fucking pathetic.',
  'Poor people.',
  'Only dating Asian women.',
  'Putting children in cages.',
  'Karen.',
  'How amazing it is to be on mushrooms.',
  'Judging everyone.',
  'An all-white jury.',
  'Getting married, having a few kids, buying some stuff, retiring to Florida, and dying.',
  'Some god damn peace and quiet.',
  'AIDS.',
  'Pictures of boobs.',
  'Strong female characters.',
  'Getting decapitated by a helicopter.',
  'Hospice care.',
  'Getting really high.',
  'The opioid epidemic.',
  'Penis envy.',
  'Gay conversion therapy.',
  'Burgers and pussy.',
  'Smelling of cum.',
  'The KKK.',
  'A pangender octopus who roams the cosmos in search of love.',
  'Meth.',
  'Cyanide.',
  'Holding down a child and farting all over him.',
  'A Bop It.™',
  'A whole thing of butter.',
  'Still being a virgin.',
  'Solving problems with violence.',
  'Getting cummed on.',
  'Pixelated bukkake.',
  'A lifetime of sadness.',
  'A non-disclosure agreement.',
  'Dick pics.',
  'Racism.',
  'Menstrual rage.',
  'Sunshine and rainbows.',
  'Joe Biden.',
  'Three ounces of clean urine.',
  'Doing drugs with my kids.',
  'My gay best friend.',
  'A gossamer stream of jizz that catches the light as it arcs through the morning air.',
  'Executing a hostage every hour.',
  'The rhythms of Africa.',
  'Breaking out into song and dance.',
  'Leprosy.',
  'Gloryholes.',
  'Nipple blades.',
  'The heart of a child.',
  'Puppies!',
  'Fellowship in Christ.',
  'My wife having sex with your wife.',
  'Waking up half-naked in a Denny’s parking lot.',
  'An older woman who knows her way around the penis.',
  'Getting drugs off the street and into my body.',
  'Daniel Radcliffe’s delicious asshole.',
  'Active listening.',
  'Ethnic cleansing.',
  'Itchy pussy.',
  'Blowing my boyfriend so hard he shits.',
  'A fuck-ton of almonds.',
  'A cis man playing a trans woman.',
  'Waiting till marriage.',
  'NFTs.',
  'Pretending to be a dentist.',
  'The Devil himself.',
  'Salvation.',
  'Erectile dysfunction.',
  'My collection of Japanese sex toys.',
  'The Pope.',
  'White people.',
  'Tentacle porn.',
  'My bright pink fuckhole.',
  'How far I can get my own penis up my butt.',
  'Having anuses for eyes.',
  'Two Xanax and a bottle of wine.',
  'My pet scorpion, Tina.',
  'Danny DeVito.',
  'The magic of live theatre.',
  'Throwing a virgin into a volcano.',
  'Dwayne “The Rock” Johnson.',
  'Accepting the way things are.',
  'NBA superstar LeBron James.',
  'Listening to her problems without trying to solve them.',
  'Therapy.',
  'Being fat and stupid.',
  'Pooping back and forth. Forever.',
  'Tearing that ass up like wrapping paper on Christmas morning.',
  'More elephant cock than I bargained for.',
  'A salty surprise.',
  'The South.',
  'The violation of our most basic human rights.',
  'Saudi oil money.',
  'Consensual sex.',
  'Telling a shitty story that goes nowhere.',
  'A good, strong gorilla.',
  'Seeing my father cry.',
  'Necrophilia.',
  'Being a woman.',
  'Getting into a pretty bad car accident.',
  'Bill Nye the Science Guy.',
  'Black people.',
  'Prostate stimulation.',
  'Lunchables.™',
  'Bitches.',
  'Some punk kid who stole my turkey sandwich.',
  'Heartwarming orphans.',
  'Spirit Airlines.',
  'Bubble butt bottom boys.',
  'A bowl of mayonnaise and human teeth.',
  'Fiery poops.',
  'Saying “I love you.”',
  'Inserting a Mason jar into my anus.',
  'The true meaning of Christmas.',
  'Whatever’s in the fridge.',
  'Owning and operating a Chili’s franchise.',
  'Estrogen.',
  'Girls.',
  'The Russians.',
  'A bleached asshole.',
  'Fucking the weatherman on live television.',
  'PTSD.',
  'Dark and mysterious forces beyond our control.',
  'Smallpox blankets.',
  'Masturbating.',
  'Hobos.',
  'Queefing.',
  'My fuckslave, Reginald.',
  'Cardi B.',
  'Viagra.®',
  'Soup that is too hot.',
  'The ugliest boy in town.',
  'Explaining how vaginas work.',
  'Academy Award winner Meryl Streep.',
  'Drinking alone.',
  'Dick fingers.',
  'Multiple stab wounds.',
  'The death penalty.',
  'A supportive touch on the lower back.',
  'Anal beads.',
  'Slaughtering innocent civilians.',
  'Pulling out.',
  'Being able to talk to elephants.',
  'Horse meat.',
  'A really cool hat.',
  'Stalin.',
  'A stray pube.',
  'Worshipping that pussy.',
  'Completely unwarranted confidence.',
  'Doin’ it in the butt.',
  'My ex-wife.',
  'Tiny tits that say “Yippee!” when you touch them.',
  'Touching a pug right on his penis.',
  'A windmill full of corpses.',
  'The whole enchilada.',
  'Vladimir Putin.',
  'The Patriarchy.',
  'The glass ceiling.',
  'Vomiting seafood and bleeding anally.',
  'The American Dream.',
  'Not wearing pants.',
  'My balls on your face.',
  'Pooping in a laptop and closing it.',
  'Some bitch who loves pineapple.',
  'Foreskin.',
  'Getting crushed between Serena Williams’ thighs.',
  'Italians.',
  'A fetus.',
  'Firing a rifle into the air while balls deep in a squealing hog.',
  'Natural gas.',
  'Over 10,000 Guatemalan migrants.',
  'Toxic masculinity.',
  'My relationship status.',
  'An unwanted pregnancy.',
  // Lowercase and unpunctuated on the card itself — it is the logo, not a sentence.
  'marvel',
  'My boss.',
  'Bees?',
  'Harry Potter erotica.',
  'Giving birth to the Antichrist.',
  'Three dicks at the same time.',
  'Nazis.',
  '8 oz. of Mexican black-tar heroin.',
  'What that mouth do.',
  'Dead parents.',
  'Object permanence.',
  'Opposable thumbs.',
  'Racially-biased SAT questions.',
  'The Great Depression.',
  'Chainsaws for hands.',
  'Nicolas Cage.',
  'Like, whatever.',
  'Explosions.',
  'Not vaccinating my children because I am stupid.',
  'Our dildo.',
  'Huffing spray paint.',
  'A man on the brink of orgasm.',
  'Using a condom.',
  'Invading Poland.',
  'My vagina.',
  'Assless chaps.',
  'Murder.',
  'Sipping kombucha like a smug piece of shit.',
  'Her Majesty, Queen Elizabeth II.',
  'Black Jesus.',
  'Memes.',
  'Sex with animals.',
  'Being marginalized.',
  'Goblins.',
  'Hope.',
  'Liberals.',
  'A micropenis.',
  'Committing treason.',
  'A ball of earwax, semen, and toenail clippings.',
  'A horde of Vikings.',
  'Hot people.',
  'Seething with quiet resentment.',
  'An Oedipus complex.',
  'Geese.',
  'Extremely tight pants.',
  'Fox News.',
  'A little boy who won’t shut the fuck up about dinosaurs.',
  'Bryan Cranston, of all people.',
  'Vehicular manslaughter.',
  'Women’s suffrage.',
  'Some guy.',
  'Judge Judy.',
  'Climbing a telephone pole and becoming one with the T-Mobile network.',
  'This month’s mass shooting.',
  'Barack Obama.',
  'Illegal immigrants.',
  'My horny, horny son.',
  'The female orgasm.',
  'Heteronormativity.',
  'Crumbs all over the god damn carpet.',
  'Corporate America.',
  'The wifi password.',
  'A time-traveling Chinese general from the Shang Dynasty.',
  'A bird that shits human turds.',
  'A mopey zoo lion.',
  'Pro-life protesters.',
  'Poor life choices.',
  'My sex life.',
  'Auschwitz.',
  'Cocaine for lunch.',
  'All the dudes I’ve fucked.',
  'The clitoris.',
  'The Big Bang.',
  'Land mines.',
  'The entire Mormon Tabernacle Choir.',
  'A micropig wearing a tiny raincoat and booties.',
  'Penis breath.',
  'A gambling problem.',
  'Man meat.',
  'Me time.',
  'The Underground Railroad.',
  'Kayaking with my sluts.',
  'Boppin’ my flopper.',
  'Lumberjack fantasies.',
  'Goat.',
  'Women in yogurt commercials.',
  'Literally begging to die.',
  'Being a motherfucking sorcerer.',
  'My Black ass.',
  'Genuine human connection.',
  'Announcing that I am about to cum.',
  'Balls.',
  'Grandma.',
  'Friction.',
  'Applying topical ointment to my grandfather’s infected penis.',
  'Farting and walking away.',
  'Being a dick to children.',
  'One trillion dollars.',
  'Drowning the kids in the bathtub.',
  'Dying.',
  'Drinking out of the toilet and eating garbage.',
  'The gays.',
  'The screams… the terrible screams.',
  'Men.',
  'The bombing of Nagasaki.',
  'Fake tits.',
  'The Amish.',
  'Calling the cops on an innocent Black man.',
  'My ugly face and bad personality.',
  'A bitch slap.',
  'A brain tumor.',
  'Giggling like an anime girl.',
  'Swamp ass.',
  'The milkman.',
  'Cards Against Humanity.',
];
