/*
 * Cards Against Humanity: Family Edition (v1.1): 95 black cards, 505 white.
 *
 * Transcribed from the print-and-play PDF the publisher gives away. Unlike the
 * Main Deck's PDF this one carries real embedded text, so the cards were
 * extracted rather than read off the page — but eight of them still had to be
 * repaired by hand, because their blank is drawn as a rule rather than set as
 * underscores and no extractor can see it. Every page was then proofread
 * against the rendered original, and family.test.ts holds the counts honest.
 *
 * Unlike the Main Deck, this PDF states no licence at all. See NOTICE.md.
 *
 * Every prompt here takes exactly one card: the Family Edition prints no PICK
 * badge and has no card with two blanks.
 *
 * One white card names a website. It is a joke about a fake product, nothing
 * fetches it, and no-network.test.ts is about fetches rather than about the
 * letters — see §10 and the note in that test.
 */

import type { BlackCard } from './cards.ts';

export const BLACK: BlackCard[] = [
  {
    text: 'Papa, come quickly! There, in the garden! Do you see ____? Tell me you see it, Papa!',
    pick: 1,
  },
  {
    text: 'Attention students! Principal Butthead is at home recovering from ____. We hope he’ll be back soon.',
    pick: 1,
  },
  {
    text: 'I’m sorry, Jordan, but that’s not an acceptable Science Fair project. That’s just ____.',
    pick: 1,
  },
  {
    text: 'The warm August air was filled with change. Things were different, for Kayla was now ____.',
    pick: 1,
  },
  {
    text: 'This is gonna be the best sleepover ever. Once Mom goes to bed, it’s time for ____!',
    pick: 1,
  },
  { text: 'Coming soon! Batman vs. ____.', pick: 1 },
  { text: 'Class, pay close attention. I will now demonstrate the physics of ____.', pick: 1 },
  { text: 'Hey Riley, I’ll give you five bucks if you try ____.', pick: 1 },
  { text: 'When I look in the mirror, I see ____.', pick: 1 },
  { text: 'My dad and I enjoy ____ together.', pick: 1 },
  {
    text: 'Hey, kids. I’m Sensei Todd. Today, I’m gonna teach you how to defend yourself against ____.',
    pick: 1,
  },
  { text: 'MY NAME CHUNGO. CHUNGO LOVE ____.', pick: 1 },
  { text: 'Never fear, Captain ____ is here!', pick: 1 },
  { text: 'Kids, Dad is trying something new this week. It’s called “____.”', pick: 1 },
  { text: 'Oh, no thank you, Mrs. Lee. I’ve had plenty of ____ for now.', pick: 1 },
  { text: 'Time to put on my favorite t-shirt, the one that says “I ♥____.”', pick: 1 },
  { text: 'And over here is Picasso’s most famous painting, “Portrait of ____.”', pick: 1 },
  { text: 'The aliens are here. They want ____.', pick: 1 },
  { text: 'They call me “Mr. ____.”', pick: 1 },
  { text: 'CHUNGO FEEL SICK. CHUNGO NO LIKE ____ ANYMORE.', pick: 1 },
  { text: 'Mom!? You have to come pick me up! There’s ____ at this party!', pick: 1 },
  { text: 'CNN breaking news! Over half of Americans are now ____.', pick: 1 },
  { text: 'On the next episode of Dora the Explorer, Dora explores ____.', pick: 1 },
  { text: 'Alright, which one of you little turds is responsible for ____?!', pick: 1 },
  {
    text: 'Ladies and gentlemen, I have discovered something amazing. I have discovered ____.',
    pick: 1,
  },
  {
    text: 'And in the blue corner, weighing in at 280 pounds, it’s Tommy “____” Takahashi!',
    pick: 1,
  },
  { text: 'Outback Steakhouse: No rules. Just ____.', pick: 1 },
  { text: 'Ew. Grandpa smells like ____.', pick: 1 },
  {
    text: 'My name is Peter Parker. I was bitten by a radioactive spider, and now I’m ____.',
    pick: 1,
  },
  { text: 'Put on your helmet, strap on your goggles, and get ready for ____!', pick: 1 },
  {
    text: 'Attention students! This is Principal Butthead reminding you that we do not allow ____ in the hallway. Thank you.',
    pick: 1,
  },
  { text: 'What’s about to take this school dance to the next level?', pick: 1 },
  { text: 'Little Miss Muffet\nSat on a tuffet\nEating her curds and ____.', pick: 1 },
  { text: 'All I want for Christmas is ____.', pick: 1 },
  { text: 'Me and my friends don’t play with dolls anymore. We’re into ____ now.', pick: 1 },
  { text: 'We’re not supposed to go in the attic. My parents keep ____ in there.', pick: 1 },
  { text: 'Police! Arrest this man! He’s ____.', pick: 1 },
  { text: 'My favorite dinosaur is “____asaurus.”', pick: 1 },
  { text: 'When I pooped, what came out of my butt?', pick: 1 },
  {
    text: 'I’m not like the other children. Toys bore me, and I don’t care for sweets. I prefer ____.',
    pick: 1,
  },
  { text: 'I’m sorry, Mrs. Sanchez, but I couldn’t finish my homework because of ____.', pick: 1 },
  { text: 'Oh Dark Lord, we show our devotion with a humble offering of ____!', pick: 1 },
  {
    text: 'Thanks for watching! If you want to see more vids of ____, smash that subscribe.',
    pick: 1,
  },
  { text: 'We’re off to see the wizard, the wonderful wizard of ____!', pick: 1 },
  { text: 'What’s all fun and games until somebody gets hurt?', pick: 1 },
  { text: 'Young lady, we do not allow ____ at the dinner table.', pick: 1 },
  { text: 'Welcome! We’re glad you’re here. Now sit back, relax, and enjoy ____.', pick: 1 },
  { text: 'My favorite book is The Amazing Adventures of ____.', pick: 1 },
  { text: 'Well, look what we have here! A big fancy man walkin’ in like he’s ____.', pick: 1 },
  { text: 'ENOUGH! I will not let ____ tear this family apart!', pick: 1 },
  { text: 'Rub a dub dub, ____ in a tub!', pick: 1 },
  { text: 'Madam President, we’ve run out of time. The only option is ____.', pick: 1 },
  { text: 'I have invented a new sport. I call it “____ ball.”', pick: 1 },
  { text: 'Hey, check out my band! We’re called “Rage Against ____.”', pick: 1 },
  { text: 'Moms love ____.', pick: 1 },
  { text: 'Where do babies come from?', pick: 1 },
  { text: 'CHUNGO ANGRY. CHUNGO DESTROY ____.', pick: 1 },
  { text: 'At school, I’m just Mandy. But at summer camp, I’m “____ Mandy.”', pick: 1 },
  { text: 'Did you hear about the new Avenger? She’s ____!', pick: 1 },
  { text: 'It’s BIG. It’s SCARY. It’s ____!', pick: 1 },
  { text: 'Disney proudly presents: “____ on Ice.”', pick: 1 },
  { text: 'What really killed the dinosaurs?', pick: 1 },
  { text: 'Beep beep! ____ coming through!', pick: 1 },
  { text: 'New from McDonald’s: it’s the Mc____ Burger.', pick: 1 },
  { text: 'You don’t love me, Sam. All you care about is ____.', pick: 1 },
  { text: 'Did you know that Benjamin Franklin invented ____?', pick: 1 },
  { text: '“On the 12th day of Christmas, my true love gave to me: ____.”', pick: 1 },
  {
    text: 'The easiest way to tell me and my twin apart is that I have a freckle on my cheek and she’s ____.',
    pick: 1,
  },
  {
    text: 'Hey guys. I just want to tell all my followers who are struggling with ____: it DOES get better.',
    pick: 1,
  },
  { text: 'You’re grounded, young lady! No ____ for a whole week.', pick: 1 },
  { text: 'Princess Marigold, the kingdom is in danger! You must stop ____.', pick: 1 },
  { text: 'Shut up, Becky! At least I’m not ____.', pick: 1 },
  { text: 'I lost my arm in a ____ accident.', pick: 1 },
  { text: 'Isn’t this great, honey? Just you, me, the kids, and ____.', pick: 1 },
  { text: 'Foolish child! Did you think you could escape from ____?', pick: 1 },
  { text: 'Girls just wanna have ____.', pick: 1 },
  { text: 'Run, run, as fast as you can. You can’t catch me, I’m ____!', pick: 1 },
  { text: 'New from Mattel, it’s ____ Barbie!', pick: 1 },
  { text: 'No fair! How come Chloe gets her own phone, and all I get is ____?', pick: 1 },
  { text: 'Bow before me, for I am the Queen of ____!', pick: 1 },
  { text: 'New from Hasbro! It’s BUNGO: The Game of ____.', pick: 1 },
  {
    text: 'I don’t really know what my mom’s job is, but I think it has something to do with ____.',
    pick: 1,
  },
  { text: 'Our day at the water park was totally ruined by ____.', pick: 1 },
  { text: 'Alright, kids. The votes are in, and the new school mascot will be ____!', pick: 1 },
  { text: 'What killed Old Jim?', pick: 1 },
  { text: 'Next from J.K. Rowling: Harry Potter and the Chamber of ____.', pick: 1 },
  { text: 'What’s keeping Dad so busy in the garage?', pick: 1 },
  { text: 'Boys? No. ____? Yes!', pick: 1 },
  { text: 'ME HUNGRY. ME WANT ____.', pick: 1 },
  { text: 'Oh, that’s my mom’s friend Carl. He comes over and helps her with ____.', pick: 1 },
  { text: 'Guys, stop it! There’s nothing funny about ____.', pick: 1 },
  {
    text: 'Huddle up, Wildcats! They may be bigger. They may be faster. But we’ve got a secret weapon: ____.',
    pick: 1,
  },
  { text: 'Coming to theaters this holiday season, “Star Wars: The Rise of ____.”', pick: 1 },
  { text: 'I do not fight for wealth. I do not fight for glory. I fight for ____!', pick: 1 },
  { text: 'Come on, Danny. All the cool kids are doin’ it. Wanna try ____?', pick: 1 },
];

export const WHITE: string[] = [
  'A big wet kiss from Great Aunt Sharon.',
  'A cloud that rains diarrhea.',
  'A caveperson named Helen.',
  'Acting kinda sus.',
  'All of your teeth falling out.',
  'Beautiful Grandma.',
  'Defecating on the neighbor’s lawn.',
  'Eight hours of video games.',
  'Going night-night.',
  'Hanging out with Zendaya.',
  'Kissing Mom on the lips.',
  'Me, your dad.',
  'Playing trumpet for the Mayor.',
  'Ratzilla.',
  'Teeny tiny turds.',
  'That there tarantula.',
  'The way Grandpa smells.',
  'Three glasses of red wine.',
  'Whatever Dad does at work.',
  'Getting shot out of a cannon.',
  'Jesus.',
  'Eating pasta out of my pants.',
  'A burrito smoothie.',
  'A bear.',
  'Old people.',
  'My sister’s stupid boyfriend.',
  'Stuffing my underwear with pancakes.',
  'Stinky Martha, the superhero that nobody likes.',
  'My chainsaw.',
  'Diarrhea.',
  'Boogers.',
  'The police.',
  'Sniffing a dog’s butt.',
  'Horrible allergies.',
  'Your face.',
  'A gerbil named “Gerbil.”',
  'Fartus Magnimus, God of Beans.',
  'Rated-R stuff.',
  'Blowing up the Moon.',
  'Getting launched into space.',
  'Likes.',
  'A bird pooping on the president’s head.',
  'Chungo, the talking gorilla.',
  'The way I feel when I see Kyle.',
  'Hot gossip.',
  'Forgetting to put on underwear.',
  'Running full speed into a wall.',
  'The Russians.',
  'A black hole.',
  'Putting my butt on stuff.',
  'Racism, sexism, and homophobia.',
  'Making the bees angry.',
  'My strong, terrifying daughter.',
  'A Democrat.',
  'TikTok.',
  'Cheeto fingers.',
  'A huge honkin’ carrot.',
  'The country of Bolivia.',
  'My parents.',
  'Idiots.',
  'Filling my butt with spaghetti.',
  'Putting an apple in a little boy’s mouth and roasting him for dinner.',
  'Taking a dump in the backyard and blaming it on the dog.',
  'Climbing into a cow’s butt.',
  'Work.',
  'Mashing a banana into your belly button.',
  'China.',
  'Shrek.',
  'Cavities.',
  'Eating people.',
  'Butts of all shapes and sizes.',
  'A 40-piece Chicken McNuggets.',
  'Climate change.',
  'Barf.',
  'A poop as big as Mom.',
  'A couch that eats children.',
  'Going to Hell.',
  'The loose skin at the joint of the elbow known as “the weenus.”',
  'A horse with no legs.',
  'Fat stacks of cash.',
  'Dora the Explorer.',
  'Illegal drugs.',
  'Cold, wet garlic bread.',
  'Dad’s meatloaf.',
  'Extra-warm Pepsi.',
  'The old man with the rake who lives down the dark and winding road.',
  'Calling 9-1-1.',
  'Spending my parents’ hard-earned money.',
  'Toe jam.',
  'Hot lava.',
  'Butt surgery.',
  'Freeing all the animals from the zoo.',
  'A bountiful harvest of squashes and corns.',
  'Bombs.',
  'Boobies.',
  'Respecting personal boundaries.',
  'Having no idea what’s going on.',
  'John Wilkes Booth.',
  'Getting married.',
  'Politics.',
  'Garbage.',
  'Naked people.',
  'This stupid game.',
  'Biting a rich person.',
  'Screaming at birds.',
  'Getting stuck in the toilet.',
  'Getting crushed by a piano.',
  'Huge pants.',
  'Mom’s spaghetti.',
  'An old, dirty cat with bad breath.',
  'A corn dog.',
  'Hot wet garbage.',
  'Principal Butthead.',
  'A statue of a naked guy.',
  'A chicken that has pickles as horns and a butt the size of a bus.',
  'Joining the army.',
  'Witchcraft.',
  'Taking out my eyeballs.',
  'Sacrificing Uncle Tim.',
  'Moving to Ohio.',
  'A hundred screaming monkeys.',
  'A dinosaur that is pooping but doesn’t know it is pooping.',
  'Emotions.',
  'Ham.',
  'Clams.',
  'Spider-Man.',
  'Drinking out of the toilet and eating garbage.',
  'Trying to catch that dang raccoon.',
  'Slapping my huge belly.',
  'The doll that watches me sleep.',
  'Money.',
  'LeBron James.',
  'Divorce.',
  'Me.',
  'Salmon.',
  'Screaming the F-word.',
  'A whole thing of cottage cheese.',
  'Crab-walking from the toilet to get more toilet paper.',
  'Mayonnaise.',
  'Total world domination.',
  'Failure.',
  'JoJo Siwa.',
  'Getting kicked in the nuts.',
  'Farting and walking away.',
  'Sharks with legs.',
  'Triangles.',
  'Ninjas.',
  'The floor.',
  'The whole family.',
  'Bench pressing a horse.',
  'Spiders.',
  'Uranus.',
  'A Republican.',
  'Giving wedgies to my haters.',
  '“Baby Shark” on repeat forever.',
  'Big Randy.',
  'Blasting my math teacher into the sun.',
  'Dreaming about boys.',
  'Taking a dump in the pool.',
  'Crying in the bathroom.',
  'Happiness.',
  'Poison.',
  'Hot, juicy broccoli farts.',
  'A scoop of tuna.',
  'Doing karate.',
  'Eating bicycles to somehow become famous.',
  'Lil Nas X.',
  'Dad’s famous poops.',
  'Squirty cheese.',
  'My girlfriend, who goes to another school.',
  'Having too many fingers.',
  'Slapping that butt.',
  'Questioning authority.',
  'Chugging a gallon of milk and then vomiting a gallon of milk.',
  'Farting a lot today.',
  'Going bald.',
  'Germs.',
  'Nuclear war.',
  'Barfing into a popcorn bucket.',
  'A cursed llama with no eyes.',
  'The wettest fart you ever heard.',
  'Shaving Dad’s back.',
  'Overthrowing the government.',
  'Murdering.',
  'Exploding.',
  'Bleeding.',
  'The oppressive system of capitalism.',
  'Saying “I love you.”',
  'A long, hot pee.',
  'Throwing up double peace signs with your besties at Starbucks.',
  'A balloon filled with chili.',
  'Stealing dead bodies from the morgue.',
  'The freedom of speech.',
  'Egg salad.',
  'Mom’s friend, Donna.',
  'Rich people.',
  'Pirate music.',
  'Being a dinosaur.',
  'A fake kid made out of wood.',
  'Homework.',
  'Batman.',
  'A dead body.',
  'Drinking a whole bottle of ranch.',
  'Destroying the planet.',
  'Living in a pineapple under the sea.',
  'Lovingly placing two bagel bites over the eyes of my dead brother.',
  'This pumpkin.',
  'Extremely tight underpants.',
  'A nice, warm glass of pee.',
  'Magical corn that makes you fart rainbows.',
  'Complaining.',
  'Bursting into flames.',
  'Poop from the sky.',
  'My whole body getting big and strong and beautiful.',
  'Big, juicy pimples.',
  'The humble earthworm.',
  'The garbage man.',
  'A big, and I mean BIG turtle.',
  'Your mom!',
  'The octopus stuck to my face.',
  'Dying of old age.',
  'Pantaloons.',
  'Screaming into a can of Pringles.',
  'Grandpa.',
  'Shutting up.',
  'Silence.',
  'My annoying brother.',
  'My future husband.',
  'A hot air balloon powered by fart gas.',
  'Sitting on the toilet and going poop.',
  'A screaming soccer dad.',
  'Cocktail weenies.',
  'The British.',
  'WAR!',
  'Science.',
  'Picking my nose and eating it.',
  'Having a really big head.',
  'A dead whale.',
  'Eating a burger while farting on a manatee.',
  'The power of the Dark Side.',
  'Big butt cheeks filled with poop.',
  'My friend Steve.',
  'Violence.',
  'Going live on Zoom without pants on.',
  'Eating toenail clippings.',
  'Using balloons as boobies.',
  'My dang kids.',
  'Squeezing a lemon into my eye.',
  'Tombus, the talking rhombus.',
  'Eating a rock, getting the rock stuck in your stomach, swallowing a second rock to push out the first rock, then getting that rock stuck, and then having to go to the emergency room.',
  'Ellen.',
  'Uncle Bob.',
  'Outback Steakhouse.',
  'Dwayne “The Rock” Johnson.',
  'A baby with a full mustache.',
  'Getting hit in the face with a soccer ball.',
  'Eating a whole roll of toilet paper.',
  'The bacon.',
  'The first female president of the United States.',
  'Falling off a mountain.',
  'Person milk.',
  'Pink eye.',
  'Pork.',
  'The government.',
  'JOHN CENAAAA!',
  'Nothing.',
  'GOOOAAALLLL!!!',
  'Mom’s new haircut.',
  'Happy daddies with happy sandals.',
  'Giggling and farting and slurping milkshakes.',
  'Ice pee.',
  'Obama.',
  'Twerking.',
  'Reading my sister’s diary.',
  'The ice cream man.',
  'Love.',
  'Raisins.',
  'Living in the dumpster.',
  'Having a baby.',
  'Shoplifting.',
  'My father, who is a walrus.',
  'The dentist.',
  'Aunt Linda.',
  'One tough mama.',
  'Releasing the falcons!',
  'Literally ruining my life.',
  'Flushing myself down the toilet.',
  'Fire farts.',
  'Lice.',
  'A big, fat, wiggly, squishy, talking, screaming turd.',
  'Anti-vaxxers.',
  'Wiping my butt.',
  'Saying mean stuff and making people feel bad.',
  'Beyoncé.',
  'A truck.',
  'Only beans.',
  'The beautiful potato.',
  'Legs.',
  'The woman I’m going to marry one day.',
  'Unleashing a hell demon that will destroy our world.',
  'Feminism.',
  'Lighting stuff on fire.',
  'Turning 40.',
  'Getting a skull tattoo.',
  'An invisible giant who takes giant, visible poops.',
  'A cowboy who is half boy, half cow.',
  'The longest tongue in the world.',
  'Josh.',
  'Locking Mother in the pantry.',
  'Ariana Grande.',
  'Puberty.',
  'A glorious beard.',
  'A dog that stares into eternal nothingness.',
  'Dumbness.',
  'Farting, barfing, and passing out.',
  'Flamin’ Hot Cheetos.',
  'Peeing in a glorious golden arc.',
  'Eating a ham and cheese sandwich on March 24, 2022.',
  'Niagara Falls, but with diarrhea instead of water.',
  'My ex-wife.',
  'Using my butt as a microwave.',
  'Glen’s fabulous body.',
  'Gluten.',
  'Who cares.',
  'Many wolves.',
  'One long hair growing out of a mole.',
  'A butt that eats underwear.',
  'Poo-poo.',
  'Mooing.',
  'Meat blindness.',
  'Punching everyone.',
  'How much wood a woodchuck would chuck if a woodchuck could chuck wood.',
  'Swords.',
  'Kevin’s mom.',
  'Getting scalded in the face with hot beans.',
  'Chest hair.',
  'My annoying sister.',
  'Getting slapped with a fish.',
  'Harry Potter.',
  'Peeing sand.',
  'Being French, hoh-hoh-hoh!',
  'Guacamole.',
  'Getting naked.',
  'A super angry cat I found outside.',
  'Slappy Spatchy, the game where you slap each other with spatulas. Learn more at www.SlappySpatchy.com.',
  'A pregnant person.',
  'A bunch of dead squirrels on a trampoline.',
  'Grandma panties.',
  'Thick, nasty burps.',
  'Having no bones.',
  'Famous peanut scientist George Washington Carver.',
  'Saving up my boogers for ten years and then building the world’s largest booger.',
  'Swallowing a bunch of popcorn kernels and shooting them out of my butt like a machine gun.',
  'A hug.',
  'The Dark Lord.',
  'Being super serious right now.',
  'Freeing a fart from its butt prison.',
  'An order of mozzarella sticks.',
  'Fake news.',
  'The baby.',
  'Like a million alligators.',
  'Big, slappy hands.',
  'Beer.',
  'Spit.',
  'The fifth graders.',
  'Licking a goat.',
  'A flamethrower.',
  'Drama!',
  'Old Jim’s Steamy Butt Sauce.',
  'Going to the emergency room.',
  'Sitting atop a pile of tuna, like some kind of tuna queen.',
  'Girls.',
  'A Pringle.',
  'Never showering.',
  'Hunky men.',
  'The gym teacher.',
  'Coming back from the dead.',
  'Burning books.',
  'Deep-frying Dad’s laptop.',
  'Violating the dress code.',
  'Building a ladder of hot dogs to the moon.',
  'Practicing kissing.',
  'Eating a lightning bug to gain its lightning powers.',
  'Slowly turning into cheese.',
  'Whispering secrets to my best friend, Turkey.',
  'Ear wax.',
  'Knives.',
  'Stuff.',
  'Taking a selfie.',
  'Dancing with my son.',
  'Punching a guy through a wall.',
  'Nipples.',
  'Cat pee.',
  'Cringe.',
  'Billie Eilish.',
  'Really bad Dad jokes.',
  'Elegant party hats.',
  'Santa Claus.',
  'The gluteus maximus.',
  'Baby Yoda.',
  'Peeing in the cat’s litter box.',
  'A big sad dragon with no friends.',
  'A big whiny cry-baby.',
  'Seymour Butts.',
  'The bus driver.',
  'Getting run over by a train.',
  'Spinning and barfing.',
  'Some freakin’ privacy.',
  'Butt hair.',
  'Having many husbands.',
  'Making the bathroom smell.',
  'Coffee.',
  'Anime.',
  'The sweet honking of Karen’s bassoon.',
  'Pooping in a bag and lighting it on fire.',
  'Space lasers.',
  'Being dead.',
  'Pooping barf forever.',
  'FOOOOD FIIIIIIIIIIIIIIIIIGHT!!!',
  'Wearing high heels.',
  'A long, long snake.',
  'Getting trampled by horses.',
  'The babysitter.',
  'The lunch lady.',
  'Peeing on my poopy.',
  'Not wearing pants.',
  'Meatballs, meatballs, meatballs!',
  'Finding Waldo.',
  'Going around sniffing people’s armpits.',
  'Stealing Mom’s credit card.',
  'Diaper beans.',
  'Cigarettes.',
  'Getting my ponytail stuck in my butt.',
  'Looking into people’s windows.',
  'Sucking at life.',
  'Covering my body with vaseline and sliding on the floor like a slug.',
  'Evil.',
  'A big rock.',
  'Rubbing lotion on a hairless cat.',
  'Goblins.',
  'Nasty Cousin Amber.',
  'Tongue kissing.',
  'Abraham Lincoln.',
  'Covering myself with ketchup and mustard because I am hot dog.',
  'Hot, fresh doodies.',
  'Feet.',
  'Sadness.',
  'Going beast mode.',
  'An owl that hates you.',
  'A doll that pees real pee!',
  'A naked lady in a painting.',
  'Chunks.',
  'Some weird guy.',
  'Getting a girlfriend.',
  'Falling in love with a hot dog.',
  'Throwing stuff at other stuff.',
  'Hogs.',
  'A turd that just won’t flush.',
  'The entire state of Texas.',
  'Showing everyone my butt.',
  'My big donkey brother.',
  'The huge, stupid moon.',
  'Math.',
  'Pee-pee.',
  'Dinner.',
  'Butthole.',
  'Smelling like onions.',
  'Being fake.',
  'Peer pressure.',
  'Peeing in my backpack.',
  'Bad parenting.',
  'Mom’s butt.',
  'One weird lookin’ toe.',
  'You.',
  'Boys.',
  'Sitting on a cake.',
  'Teaching a chicken to kill.',
  'The middle finger.',
  'A bra.',
  'Being famous on YouTube.',
  'Cream.',
  'Balls.',
  'Having no friends.',
  'Peeing into everyone’s mouth.',
  'Gluing my butt cheeks together.',
  'How school slowly breaks your spirit and drains your will to live.',
  'A Pokémon named “Jim.”',
  'True love’s kiss.',
  'Total crap.',
  'Cool sunglasses.',
  'Literally dying from the smell of a fart.',
  'Snot bubbles.',
  'Doing crimes and going to jail.',
  'This goat, who is my friend.',
  'Aliens.',
  'School.',
  'A cow.',
  'The terrible winter of 1609.',
  'Getting sucked into a jet engine.',
  'Not breathing.',
  'Licking a used band-aid.',
  'Braiding my armpit hair.',
  'Waking up inside of a spider web.',
  'An eggy smell.',
  'Getting hit by an airplane.',
];
